---
  name: Semantic Release

  on:
    push:
      branches:
        - main
        - beta
    workflow_dispatch:

  jobs:
    release:
      runs-on: ubuntu-latest
      concurrency: release
      permissions:
        id-token: write
        contents: write

      steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry nox

      - name: Publish distribution 📦 to PyPI
        run: |
          nox -rs release -- "$PYPI_PASSWORD"
        env:
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
